# Generated by Django 5.0.1 on 2024-02-04 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_svg', models.TextField(verbose_name='Social SVG Code')),
                ('social_link', models.URLField(verbose_name='Link')),
                ('social_name', models.CharField(max_length=100, verbose_name='Social Name')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Display these tags.')),
                ('hero_heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='Hero Heading')),
                ('hero_para', models.TextField(blank=True, null=True, verbose_name='Hero Body')),
                ('what_heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='"What is section" Heading')),
                ('what_para', models.TextField(blank=True, null=True, verbose_name='"What is section" Body')),
                ('how_heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='"How to section" Heading')),
                ('how_para', models.TextField(blank=True, null=True, verbose_name='"How to section" Body')),
                ('how_step_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 1')),
                ('how_step_1_body', models.TextField(blank=True, null=True, verbose_name='How to Step 1 Body')),
                ('how_step_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 2')),
                ('how_step_2_body', models.TextField(blank=True, null=True, verbose_name='How to Step 2 Body')),
                ('how_step_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 3')),
                ('how_step_3_body', models.TextField(blank=True, null=True, verbose_name='How to Step 3 Body')),
                ('how_step_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 4')),
                ('how_step_4_body', models.TextField(blank=True, null=True, verbose_name='How to Step 4 Body')),
                ('how_step_5', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 5')),
                ('how_step_5_body', models.TextField(blank=True, null=True, verbose_name='How to Step 5 Body')),
                ('how_step_6', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 6')),
                ('how_step_6_body', models.TextField(blank=True, null=True, verbose_name='How to Step 6 Body')),
                ('how_step_7', models.CharField(blank=True, max_length=500, null=True, verbose_name='How to Step 7')),
                ('how_step_7_body', models.TextField(blank=True, null=True, verbose_name='How to Step 7 Body')),
                ('how_to_closure', models.TextField(blank=True, null=True, verbose_name='How to Closure Body')),
                ('benefits_heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='"Benefits section" Heading')),
                ('benefits_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits 1')),
                ('benefits_1_body', models.TextField(blank=True, null=True, verbose_name='Benefits 1 Body')),
                ('benefits_1_svg', models.TextField(blank=True, null=True, verbose_name='Benefits 1 SVG Code')),
                ('benefits_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits 2')),
                ('benefits_2_body', models.TextField(blank=True, null=True, verbose_name='Benefits 2 Body')),
                ('benefits_2_svg', models.TextField(blank=True, null=True, verbose_name='Benefits 2 SVG Code')),
                ('benefits_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits 3')),
                ('benefits_3_body', models.TextField(blank=True, null=True, verbose_name='Benefits 3 Body')),
                ('benefits_3_svg', models.TextField(blank=True, null=True, verbose_name='Benefits 3 SVG Code')),
                ('benefits_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Benefits 4')),
                ('benefits_4_body', models.TextField(blank=True, null=True, verbose_name='Benefits 4 Body')),
                ('benefits_4_svg', models.TextField(blank=True, null=True, verbose_name='Benefits 4 SVG Code')),
                ('special_heading', models.CharField(blank=True, max_length=500, null=True, verbose_name='"Special  section" Heading')),
                ('special_para', models.TextField(blank=True, null=True, verbose_name='"Special  section" Body')),
                ('special_point_1', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special  Point 1')),
                ('special_point_1_body', models.TextField(blank=True, null=True, verbose_name='Special  Point 1 Body')),
                ('special_point_2', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special  Point 2')),
                ('special_point_2_body', models.TextField(blank=True, null=True, verbose_name='Special  Point 2 Body')),
                ('special_point_3', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special  Point 3')),
                ('special_point_3_body', models.TextField(blank=True, null=True, verbose_name='Special  Point 3 Body')),
                ('special_point_4', models.CharField(blank=True, max_length=500, null=True, verbose_name='Special  Point 4')),
                ('special_point_4_body', models.TextField(blank=True, null=True, verbose_name='Special  Point 4 Body')),
                ('headtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.headtags', verbose_name='Headtags for Home Page')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Pages',
            },
        ),
    ]
