# Generated by Django 5.0.1 on 2024-02-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_socials_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page Content', 'verbose_name_plural': 'Home Page Contents'},
        ),
        migrations.AddField(
            model_name='socials',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Show this social'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Use this Home content'),
        ),
    ]
