# Generated by Django 5.0.1 on 2024-02-04 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_homepage_options_socials_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this content')),
                ('html_content', models.TextField()),
                ('headtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.headtags', verbose_name='Headtags for About Page')),
            ],
            options={
                'verbose_name': 'About Page Content',
                'verbose_name_plural': 'About Page Contents',
            },
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this content')),
                ('html_content', models.TextField()),
                ('headtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.headtags', verbose_name='Headtags for Contact Page')),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Contents',
            },
        ),
        migrations.CreateModel(
            name='PrivacyPolicyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this content')),
                ('html_content', models.TextField()),
                ('headtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.headtags', verbose_name='Headtags for Privacy Policy Page')),
            ],
            options={
                'verbose_name': 'Privacy Policy Page Content',
                'verbose_name_plural': 'Privacy Policy Page Contents',
            },
        ),
        migrations.CreateModel(
            name='TermsAndConditionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Show this content')),
                ('html_content', models.TextField()),
                ('headtags', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.headtags', verbose_name='Headtags for Terms & Conditions Page')),
            ],
            options={
                'verbose_name': 'Terms & Conditions  Page Content',
                'verbose_name_plural': 'Terms & Conditions  Page Contents',
            },
        ),
    ]
